/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.gradleup.shadow") version "9.4.1"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.azisaba.net/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.mikeprimm.com/")
    }

    maven {
        url = uri("https://repo.onarandombox.com/multiverse-releases")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.wea-ondara.net/repository/public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

dependencies {
    api("org.bstats:bstats-bukkit:1.7")
    api("org.bstats:bstats-bungeecord:1.7")
    api("com.google.code.gson:gson:2.8.9")
    api("org.apache.commons:commons-lang3:3.18.0")
    api("org.jetbrains:annotations:20.1.0")
    testImplementation("junit:junit:4.13.1")
    compileOnly("org.spigotmc:spigot-api:1.16.2-R0.1-SNAPSHOT")
    compileOnly("net.luckperms:api:1.16-R0.2-SNAPSHOT") {
        exclude("net.md-5", "brigadier")
    }
    compileOnly("net.md-5:bungeecord-chat:1.16-R0.3")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7") {
        exclude("org.bukkit", "bukkit")
    }
    compileOnly("org.dynmap:dynmap-api:2.0") {
        exclude("org.bukkit", "bukkit")
    }
    compileOnly("com.onarandombox.multiversecore:Multiverse-Core:4.3.9") {
        exclude("me.main__.util", "SerializationConfig")
        exclude("com.pneumaticraft.commandhandler", "CommandHandler")
        exclude("com.dumptruckman.minecraft", "buscript")
        exclude("com.dumptruckman.minecraft", "Logging")
        exclude("de.themoep.idconverter", "mappings")
    }
    compileOnly("com.gmail.nossr50.mcMMO:mcMMO:2.1.146") {
        exclude("org.apache.maven.scm", "maven-scm-provider-gitexe")
        exclude("org.bstats", "bstats-bukkit")
        exclude("org.spigotmc", "spigot-api")
        exclude("com.sk89q.worldguard", "worldguard-core")
        exclude("com.sk89q.worldguard", "worldguard-legacy")
    }
    compileOnly("net.alpenblock:BungeePerms:4.0-dev-114")
    compileOnly("net.luckperms:api:5.1")
}

group = "net.azisaba"
version = "3.3.3"
description = "lunachatplus"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
