name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Prepare settings.xml
        run: |
          echo "<settings><servers><server><id>repo</id><username>${{ secrets.REPO_USERNAME }}</username><password>${{ secrets.REPO_PASSWORD }}</password></server></servers></settings>" > $HOME/deploy-settings.xml
      - name: Deploy
        run: mvn deploy -Durl=${{ secrets.REPO_SNAPSHOT_URL }} -DrepositoryId=repo -s $HOME/deploy-settings.xml
