name: Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - name: chmod gradlew
        run: chmod +x gradlew
      - name: build
        run: ./gradlew shadowJar
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: build/libs/
      - name: Prepare gradle.properties
        run: |
          mkdir -p $HOME/.gradle
          echo "repoUsername=${{ secrets.REPO_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "repoPassword=${{ secrets.REPO_PASSWORD }}" >> $HOME/.gradle/gradle.properties
      - name: Deploy
        run: ./gradlew clean test publish

      - name: Release new build
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: v${{ steps.retrieveApiVersion.outputs.version }}
          files: 'build/libs/LunaChatPlus.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
